
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - notifications/finalizers
  verbs:
  - update
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - notifications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - integrations.tekton.ornew.io
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
