apiVersion: v1
kind: Secret
metadata:
  name: github-app
data:
  private-key.pem: YWFh
---
apiVersion: integrations.tekton.ornew.io/v1alpha1
kind: Provider
metadata:
  name: github-app
spec:
  type: GitHubApp
  githubApp:
    appId: 1
    privateKey:
      secretRef:
        name: github-app
